name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        # Fallback to npm install if no lockfile is present
        continue-on-error: true

      - name: Install dependencies (no lockfile)
        if: failure()
        run: npm install

      - name: Build
        run: npm run build

      # Debug steps to help confirm the build output in GitHub Actions logs.
      - name: List workspace root
        run: ls -la

      - name: List docs folder
        run: |
          if [ -d docs ]; then
            echo "docs found:"; ls -la docs; echo "\nlisting docs assets:"; ls -la docs/assets || true
          else
            echo "docs not found"; exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite is configured to build into `docs` (see vite.config.ts),
          # so upload that folder instead of `dist`.
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
